#pragma once

#include "lvgl.h"

// autogenerated, do not modify!

class Theme {
  protected:
    const lv_img_dsc_t *ui_img_initscreen2;
    const lv_img_dsc_t *ui_img_miningscreen2;
    const lv_img_dsc_t *ui_img_portalscreen;
    const lv_img_dsc_t *ui_img_btcscreen;
    const lv_img_dsc_t *ui_img_settingsscreen;
    const lv_img_dsc_t *ui_img_splashscreen2;
    const lv_img_dsc_t *ui_img_globalStats;

  public:
    // Getters
    const lv_img_dsc_t *getInitscreen2() const {
        return ui_img_initscreen2;
    }

    const lv_img_dsc_t *getMiningscreen2() const {
        return ui_img_miningscreen2;
    }

    const lv_img_dsc_t *getPortalscreen() const {
        return ui_img_portalscreen;
    }

    const lv_img_dsc_t *getBtcscreen() const {
        return ui_img_btcscreen;
    }

    const lv_img_dsc_t *getSettingsscreen() const {
        return ui_img_settingsscreen;
    }

    const lv_img_dsc_t *getSplashscreen2() const {
        return ui_img_splashscreen2;
    }

    const lv_img_dsc_t *getGlobalstats() const {
        return ui_img_globalStats;
    }

    // Setters
    void setInitscreen2(const lv_img_dsc_t *img) {
        ui_img_initscreen2 = img;
    }

    void setMiningscreen2(const lv_img_dsc_t *img) {
        ui_img_miningscreen2 = img;
    }

    void setPortalscreen(const lv_img_dsc_t *img) {
        ui_img_portalscreen = img;
    }

    void setBtcscreen(const lv_img_dsc_t *img) {
        ui_img_btcscreen = img;
    }

    void setSettingsscreen(const lv_img_dsc_t *img) {
        ui_img_settingsscreen = img;
    }

    void setSplashscreen2(const lv_img_dsc_t *img) {
        ui_img_splashscreen2 = img;
    }

    void setGlobalStats(const lv_img_dsc_t *img) {
        ui_img_globalStats = img;
    }
};

// Generic splashscreen is directly referenced by ui.cpp
//LV_IMG_DECLARE(ui_img_Generic_splashscreen2_png);

// NerdQaxePlus2 theme
LV_IMG_DECLARE(ui_img_NerdQaxePlus2_initscreen2_png);
LV_IMG_DECLARE(ui_img_NerdQaxePlus2_miningscreen2_png);
LV_IMG_DECLARE(ui_img_NerdQaxePlus2_portalscreen_png);
LV_IMG_DECLARE(ui_img_NerdQaxePlus2_btcscreen_png);
LV_IMG_DECLARE(ui_img_NerdQaxePlus2_settingsscreen_png);
LV_IMG_DECLARE(ui_img_NerdQaxePlus2_splashscreen2_png);
LV_IMG_DECLARE(ui_img_NerdQaxePlus2_globalStats_png);

// NerdQaxePlus2 theme class
class ThemeNerdqaxeplus2 : public Theme {
public:
    ThemeNerdqaxeplus2() {
        setInitscreen2(&ui_img_NerdQaxePlus2_initscreen2_png);
        setMiningscreen2(&ui_img_NerdQaxePlus2_miningscreen2_png);
        setPortalscreen(&ui_img_NerdQaxePlus2_portalscreen_png);
        setBtcscreen(&ui_img_NerdQaxePlus2_btcscreen_png);
        setSettingsscreen(&ui_img_NerdQaxePlus2_settingsscreen_png);
        setSplashscreen2(&ui_img_NerdQaxePlus2_splashscreen2_png);
        setGlobalStats(&ui_img_NerdQaxePlus2_globalStats_png);
    }
};
